# Generated by Django 6.0.2 on 2026-02-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('COMIDA', 'Comida'), ('DIVERSION', 'Objetos de Diversión'), ('USO', 'Objetos de Uso')], max_length=20)),
                ('vendedor_nombre', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
